name: dhriti
description: An open source software to extract texts from PDF and Images.
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=2.18.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.1
  google_fonts: ^4.0.3
  file_picker: ^5.2.5
  dio: ^5.0.0
  http_parser: ^4.0.2
  internet_file: ^1.2.0
  flutter_quill: ^7.0.1
  pdf: ^3.10.1
  path_provider: ^2.0.14
  intl: ^0.18.0
  timeago: ^3.3.0
  open_app_file: ^4.0.1
  image_picker: ^0.8.7+4
  delta_to_pdf:
    git:
      url: https://github.com/sabeeralikp/delta_to_pdf.git
      ref: master
  provider: ^6.0.5
  dartdoc: ^6.2.2
  flutter_rating_bar: ^4.0.1
  pdfx: ^2.4.0
  flutter_tesseract_ocr: ^0.4.24
  url_launcher: ^6.1.14
  ionicons: ^0.2.2
  in_app_update: ^4.2.2
  flutter_exif_rotation: ^0.5.1
  flutter_expandable_fab: ^2.0.0
  just_audio: ^0.9.36
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/file_upload.svg
    - assets/background/file_upload_ocr.svg
    - assets/icons/cloud_upload.svg
    - assets/icons/pdf.svg
    - assets/icons/HTR.svg
    - assets/icons/OCR.svg
    - assets/logo/ICFOSS_Logo.png
    - assets/logo/dhrithiLogo.png
    - assets/font/mandharam/mandharam_regular.ttf
    - assets/font/mandharam/mandharam_bold.ttf
    - assets/font/mandharam/mandharam_italic.ttf
    - assets/font/mandharam/mandharam_bold_italic.ttf
    - assets/tessdata_config.json
    - assets/tessdata/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
