///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
/// [Changes in segment page]
/// [author] Sabeerali
/// [since]	v0.0.1
/// [version]	v1.0.0	(March 21st, 2023 3:02 PM) 
///
class Cordinates {
/*
{
  "x": 1142,
  "y": 2173,
  "w": 158,
  "h": 27
} 
*/

  int? x; /// The x-coordinate.
  int? y; /// The y-coordinate.
  int? w; /// The width.
  int? h; /// The height.
  int? p;
  int? imgH; /// Image height property 'imgH'.
  int? imgW; /// Image width property 'imgW'.
  int? uploadHTR; /// Upload height property 'uploadHTR'.
/// Constructor for creating a `Cordinates` instance.
///
/// [x], [y], [w], [h], [p], [imgH], and [imgW] are optional parameters that
/// represent the coordinates and properties.
  Cordinates({this.x, this.y, this.w, this.h, this.p, this.imgH, this.imgW});
/// Creates a `Cordinates` instance from a JSON map.
///
/// The [json] parameter is a Map<String, dynamic> representing the JSON data.  
  Cordinates.fromJson(Map<String, dynamic> json) {
    x = json['x']?.toInt();
    y = json['y']?.toInt();
    w = json['w']?.toInt();
    h = json['h']?.toInt();
    p = json['p']?.toInt();
    imgH = json['img_h']?.toInt();
    imgW = json['img_w']?.toInt();
    uploadHTR = json['upload_htr']?.toInt();
  }
/// Converts this `Cordinates` instance to a JSON map.  
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['x'] = x;
    data['y'] = y;
    data['w'] = w;
    data['h'] = h;
    data['p'] = p;
    data['img_h'] = imgH;
    data['img_w'] = imgW;
    data['upload_htr'] = uploadHTR;

    return data;
  }
/// Converts a list of JSON data into a list of `Cordinates` instances.
///
/// The [list] parameter is a List<dynamic> containing the JSON data for multiple coordinates.
  static List<Cordinates> listFromJson(List<dynamic> list) {
    List<Cordinates> rows = list.map((i) => Cordinates.fromJson(i)).toList();
    return rows;
  }
}
