///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Cordinates {
/*
{
  "x": 1142,
  "y": 2173,
  "w": 158,
  "h": 27
} 
*/

  int? x;
  int? y;
  int? w;
  int? h;
  int? p;
  int? imgH;
  int? imgW;
  int? uploadHTR;

  Cordinates({this.x, this.y, this.w, this.h, this.p, this.imgH, this.imgW});
  Cordinates.fromJson(Map<String, dynamic> json) {
    x = json['x']?.toInt();
    y = json['y']?.toInt();
    w = json['w']?.toInt();
    h = json['h']?.toInt();
    p = json['p']?.toInt();
    imgH = json['img_h']?.toInt();
    imgW = json['img_w']?.toInt();
    uploadHTR = json['upload_htr']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['x'] = x;
    data['y'] = y;
    data['w'] = w;
    data['h'] = h;
    data['p'] = p;
    data['img_h'] = imgH;
    data['img_w'] = imgW;
    data['upload_htr'] = uploadHTR;

    return data;
  }

  static List<Cordinates> listFromJson(List<dynamic> list) {
    List<Cordinates> rows = list.map((i) => Cordinates.fromJson(i)).toList();
    return rows;
  }
}
